kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim3
  namespace: dynamic-nfs-test
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi