apiVersion: v1
kind: Service
metadata:
  name: dynamic-nfs-test
  namespace: dynamic-nfs-test
  labels:
    app: test-nfs-deployment3
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: test-nfs-deployment3