apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-dynamic-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-dynamic-storage-provisioner
            - name: NFS_SERVER
              value: xx.xx.xx.xx   #ip of nfs server
            - name: NFS_PATH
              value: /mnt/nfs_dynamic
      volumes:
        - name: nfs-client-root
          nfs:
            server: xx.xx.xx.xx   #ip of nfs server
            path: /mnt/nfs_dynamic